name: Подготовка релиза и публикация в хабе 

on:
    release:
        types: [published, edited]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        oscript_version: ['1.2.0']
    steps:
      - uses: actions/checkout@v2
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.0
        with:
          version: ${{ matrix.oscript_version }}
      - name: Установка зависимостей
        run: |
          opm install opm
          opm install xml-parser@0.1.1 && opm install 1connector@2.1.3
      - name: Сборка пакета
        run: opm build
      - name: Заливка артифактов
        uses: actions/upload-artifact@v2
        with:
          name: crs-api.zip
          path: ./crs-api-*.ospx
      - name: Заливка в релиз
        uses: AButler/upload-release-assets@v1.0
        with:
          files: ./crs-api-*.ospx
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Публикация в hub.oscript.io
        shell: bash
        run: opm push -f ./crs-api-*.ospx --token ${{ env.TOKEN }} -c stable
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}